name: yatir_viz_github
channels:
  - conda-forge
  - defaults
dependencies:
#  - hvplot  # installing from github until PR 428 is merged
  - ipykernel
  - ipython
  - jupyter
  - jupytext
  - ipykernel
  - matplotlib
  - xarray
  - panel
  - pip
  - python=3.7
  - netCDF4  #required by xarray but not automatically installed
  - pip:
      - git+https://github.com/Timothy-W-Hilton/hvplot@title_format

# prefix: /global/homes/t/twhilton/.conda/envs/yatir_viz_minimal
